/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrafoApplication;

import com.google.gson.Gson;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Torbjörn
 */
public class JFrameTestStuff extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTestStuff
     */
    public JFrameTestStuff() {
        initComponents();
        RestoreWorkbench();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneTrafos = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuNew = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFile.setText("File");

        jMenuOpen.setText("Open");
        jMenuFile.add(jMenuOpen);

        jMenuNew.setText("New");
        jMenuNew.setSelected(true);
        jMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuNew);

        jMenuSave.setText("Save workbench");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSave);

        jMenuBar1.add(jMenuFile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneTrafos, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneTrafos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewActionPerformed
        // TODO add your handling code here:
        insertNewTrafo();
    }//GEN-LAST:event_jMenuNewActionPerformed

    private void RestoreWorkbench(){
        Gson g = new Gson();
        WorkbenchManager wbm = null;
                
        
        try{
            String path = new File(".").getCanonicalPath()+"\\workbench.json";
        
       
            File file = new File(path);
        
            FileReader fileReader = new FileReader(file);
            StringBuffer stringBuffer = new StringBuffer();
            int numCharsRead;
            char[] charArray = new char[1024];
            while ((numCharsRead = fileReader.read(charArray)) > 0) {
                    stringBuffer.append(charArray, 0, numCharsRead);
            }
            fileReader.close();
            wbm = g.fromJson(stringBuffer.toString(), WorkbenchManager.class);
                    
        }catch(IOException e)
        {System.out.println(e.getMessage()); }        
        
        if(wbm  != null){
            for(int i=0; i<wbm.getWork().size(); i++)
            {
                NewJPanel t = new NewJPanel();
                jTabbedPaneTrafos.insertTab("New TRAFO", null, t,"",0);
                t.setTrafo(wbm.getWork().get(i));

            }
        }
        else{
            insertNewTrafo();
        }
        
    }
    
    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        // Spara workbench; alla öppna flikar
        // Testa att skriva JSON till fil...
        Gson g = new Gson();

        int tabs = jTabbedPaneTrafos.getTabCount();
        WorkbenchManager wbm = new WorkbenchManager();
        for(int i=0; i<tabs; i++)
        {
            NewJPanel t = (NewJPanel)jTabbedPaneTrafos.getComponentAt(i);
            wbm.getWork().add(t.getTrafo());            
        }
        
        try{
        String path = new File(".").getCanonicalPath()+"\\workbench.json";
        
        File file = new File(path);
        FileWriter fileWriter = new FileWriter(file);
        
        fileWriter.write(g.toJson(wbm));
        
        fileWriter.flush();
        fileWriter.close();
        
        
        }catch(Exception e)
        {}
        
        //Person person = g.fromJson("{\"name\": \"John\"}", Person.class);
        //System.out.println(person.name); //John
        
        /*WorkbenchManager wbm = new WorkbenchManager();
        
        TrafoWorkbench twb = new TrafoWorkbench();
        twb.setTitle("trafo 1");
        twb.setCommand("sentence");
        wbm.getWork().add(twb);
        
        twb = new TrafoWorkbench();
        twb.setTitle("trafo 2");
        twb.setCommand("test");
        wbm.getWork().add(twb);
        
        
        System.out.println(g.toJson(wbm)); // {"name":"John"}
        */
        
    }//GEN-LAST:event_jMenuSaveActionPerformed

    public void insertNewTrafo()
    {
        jTabbedPaneTrafos.insertTab("New TRAFO", null, new NewJPanel(),"",0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestStuff().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuNew;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JTabbedPane jTabbedPaneTrafos;
    // End of variables declaration//GEN-END:variables
}
