/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrafoApplication;

import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import org.jpl7.Term;

/**
 *
 * @author Torbjörn
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        TrafoCore.initializeTrafo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog1 = new javax.swing.JDialog();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCapture = new javax.swing.JTextField();
        jButtonCapture = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelTargetFilePath = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelRuleFilename = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPaneRules = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        dynamicTreeCapture = new TrafoApplication.DynamicTree();
        jPanel5 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneTarget = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPaneOutput = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jCheckBoxGenerate = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(731, 300));

        jLabel1.setText("Capture");

        jTextFieldCapture.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jTextFieldCapture.setText("test");

        jButtonCapture.setText("Go");
        jButtonCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaptureActionPerformed(evt);
            }
        });

        jLabel2.setText("Target file");
        jLabel2.setToolTipText("");

        jLabelTargetFilePath.setText("none");

        jTabbedPane2.setMinimumSize(new java.awt.Dimension(300, 300));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel3.setBackground(new java.awt.Color(153, 255, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(330, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 1000));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelRuleFilename.setText("noname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabelRuleFilename, gridBagConstraints);

        jButton2.setText("New");
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setText("Save");
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(jButton3, gridBagConstraints);

        jButton4.setText("Open");
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(jButton4, gridBagConstraints);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(202, 200));

        jEditorPaneRules.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jEditorPaneRules.setMinimumSize(new java.awt.Dimension(106, 200));
        jEditorPaneRules.setName(""); // NOI18N
        jEditorPaneRules.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane3.setViewportView(jEditorPaneRules);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 11.0;
        jPanel3.add(jScrollPane3, gridBagConstraints);

        jTabbedPane2.addTab("Rules", jPanel3);

        dynamicTreeCapture.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dynamicTreeCapture, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dynamicTreeCapture, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Capture", jPanel4);

        jSplitPane2.setLeftComponent(jTabbedPane2);

        jPanel5.setPreferredSize(new java.awt.Dimension(386, 315));

        jSplitPane3.setDividerLocation(200);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setMinimumSize(new java.awt.Dimension(400, 200));
        jSplitPane3.setPreferredSize(new java.awt.Dimension(500, 500));
        jSplitPane3.setRequestFocusEnabled(false);

        jEditorPaneTarget.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jEditorPaneTarget);

        jSplitPane3.setTopComponent(jScrollPane1);

        jEditorPaneOutput.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(jEditorPaneOutput);

        jSplitPane3.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel5);

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxGenerate.setText("Generate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCapture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxGenerate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTargetFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCapture)
                    .addComponent(jLabel2)
                    .addComponent(jLabelTargetFilePath)
                    .addComponent(jButton1)
                    .addComponent(jCheckBoxGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            jLabelTargetFilePath.setText(fileChooser.getSelectedFile().toString());
            File file = fileChooser.getSelectedFile();
            try{
            jEditorPaneTarget.setPage(file.toURI().toURL());
            }catch(Exception e)
            {}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            jLabelRuleFilename.setText(fileChooser.getSelectedFile().toString());
            File file = fileChooser.getSelectedFile();
            try{
            jEditorPaneRules.setPage(file.toURI().toURL());
            }catch(Exception e)
            {}
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaptureActionPerformed
        SaveRulebase();
        TrafoCore.LoadRulebase(jEditorPaneRules.getPage().getPath());
        Term result = TrafoCore.CallTrawl(jTextFieldCapture.getText(), dynamicTreeCapture, jEditorPaneTarget.getText());
        jEditorPaneOutput.setText("");
        if(jCheckBoxGenerate.isSelected())
            jEditorPaneOutput.setText(TrafoCore.Construct(result));
    }//GEN-LAST:event_jButtonCaptureActionPerformed

    public TrafoWorkbench getTrafo()
    {
        TrafoWorkbench temp = new TrafoWorkbench();
        temp.setTitle("TRAFO");
        temp.setCommand(jTextFieldCapture.getText());
        if(jEditorPaneRules.getPage() != null)
            temp.setRuleFilePath(jEditorPaneRules.getPage().getPath());
        if(jEditorPaneTarget.getPage() != null)
            temp.setSourceFilePath(jEditorPaneTarget.getPage().getPath());
        
        return temp;
    }
    
    public void setTrafo(TrafoWorkbench temp)
    {
        try{
        //temp.setTitle("TRAFO");
        jTextFieldCapture.setText(temp.getCommand());
        File file = new File(temp.getRuleFilePath());
        jEditorPaneRules.setPage(file.toURI().toURL());
        file = new File(temp.getSourceFilePath());
        jEditorPaneTarget.setPage(file.toURI().toURL());
        }catch(Exception e){}
    
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            SaveRulebase();
        }catch(Exception e)
        {}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SaveRulebase() 
    {
        try{
            FileWriter writer = null;
            writer = new FileWriter(jEditorPaneRules.getPage().getPath());
            jEditorPaneRules.write(writer);
            writer.close();
        }catch(Exception e)
        {}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TrafoApplication.DynamicTree dynamicTreeCapture;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCapture;
    private javax.swing.JCheckBox jCheckBoxGenerate;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPaneOutput;
    private javax.swing.JEditorPane jEditorPaneRules;
    private javax.swing.JEditorPane jEditorPaneTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelRuleFilename;
    private javax.swing.JLabel jLabelTargetFilePath;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldCapture;
    // End of variables declaration//GEN-END:variables
}
